environment:
  matrix:

  # Windows job
  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019
    configuration: Release

matrix:
  fast_finish: true

build:
  project: SubtitleShaker.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

for:
-
  matrix:
    only:
      - job_name: Windows build
